### ISSUE TITLE
AIX client install bad substitution

### ISSUE THREAD

**Issue by ericxedge** [opscode/opscode-omnitruck#73]
looks like there is an issue on line 172 when installing on AIX.

I've tried both AIX 6 and 7.

AIX 7
# curl -L https://www.chef.io/chef/install.sh |bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18265  100 18265    0     0  69840      0 --:--:-- --:--:-- --:--:-- 70250
bash: line 172: ${uname -v}.${uname -r}: bad substitution
Unable to determine platform version!
Version:

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

# oslevel -s
7100-03-03-1415

AIX 6
# /www.chef.io/chef/install.sh |bash                  <
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 18265  100 18265    0     0  46749      0 --:--:-- --:--:-- --:--:-- 46953
bash: line 172: ${uname -v}.${uname -r}: bad substitution
Unable to determine platform version!
Version:

Please file a Bug Report at https://github.com/opscode/opscode-omnitruck/issues/new
Alternatively, feel free to open a Support Ticket at https://www.getchef.com/support/tickets
More Chef support resources can be found at https://www.getchef.com/support

Please include as many details about the problem as possible i.e., how to reproduce
the problem (if possible), type of the Operating System and its version, etc.,
and any other relevant details that might help us with troubleshooting.

# oslevel -s
6100-09-03-1415

**Comment by lamont-granquist** [comment]
dup of #72
